<<<<<<< HEAD
language: java
jdk:
- oraclejdk8
install: mvn install

=======
language: java
jdk:
- oraclejdk8
install: mvn install

>>>>>>> branch 'master' of https://github.com/ignacrescenzo/centro-medico.git
